[build]
  command = """
    set -x
    export NODE_OPTIONS="--max-old-space-size=4096"
    export DEBUG="*"
    npm install
    npm run build 2>&1 | tee build.log
  """
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18.20.6"
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"
  NETLIFY_USE_YARN = "false"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
