export const CURRENCY_LIST = [
    { code: 'USD', name: 'US Dollar' },
    { code: 'EUR', name: 'Euro' },
    { code: 'GBP', name: 'British Pound' },
    { code: 'JPY', name: 'Japanese Yen' },
    { code: 'AUD', name: 'Australian Dollar' },
    { code: 'CAD', name: 'Canadian Dollar' },
    { code: 'CHF', name: 'Swiss Franc' },
    { code: 'CNY', name: 'Chinese Yuan' },
    { code: 'INR', name: 'Indian Rupee' },
    // Add more currencies as needed
];

export const MAINTENANCE_PARTS = [
    { id: 'air_filter', name: 'Air Filter' },
    { id: 'air_conditioning', name: 'Air Conditioning' },
    { id: 'battery', name: 'Battery' },
    { id: 'timing_belt', name: 'Timing Belt/Chain' },
    { id: 'body_chassis', name: 'Body/Chassis' },
    { id: 'brake_fluid', name: 'Brake Fluid' },
    { id: 'brake_pad', name: 'Brake Pad' },
    { id: 'brakes_replacement', name: 'Brakes Replacement' },
    { id: 'cabin_air_filter', name: 'Cabin Air Filter' },
    { id: 'clutch_fluid', name: 'Clutch Fluid' },
    { id: 'clutch_system', name: 'Clutch System' },
    { id: 'cooling_system', name: 'Cooling System' },
    { id: 'engine_mount', name: 'Engine Mount' },
    { id: 'engine_repair', name: 'Engine Repair' },
    { id: 'exhaust_system', name: 'Exhaust System' },
    { id: 'fuel_filter', name: 'Fuel Filter' },
    { id: 'fuel_pump', name: 'Fuel Pump' },
    { id: 'garnis_embrayage', name: 'Garnis Embrayage' },
    { id: 'glass_mirror', name: 'Glass/Mirror' },
    { id: 'heating_system', name: 'Heating System' },
    { id: 'horn', name: 'Horn' },
    { id: 'inspection', name: 'Inspection' },
    { id: 'labor_cost', name: 'Labor Cost' },
    { id: 'lights', name: 'Lights' },
    { id: 'tires', name: 'Tires' },
    { id: 'oil_change', name: 'Oil Change' },
    { id: 'oil_filter', name: 'Oil Filter' },
    { id: 'radiator', name: 'Radiator' },
    { id: 'seat_belt', name: 'Seat Belt' },
    { id: 'spark_plugs', name: 'Spark Plugs' },
    { id: 'steering_system', name: 'Steering System' },
    { id: 'suspension_system', name: 'Suspension System' },
    { id: 'technical_control', name: 'Technical Control' },
    { id: 'tire_pressure', name: 'Tire Pressure' },
    { id: 'tire_rotation', name: 'Tire Rotation' },
    { id: 'transmission_fluid', name: 'Transmission Fluid' },
    { id: 'wheel_alignment', name: 'Wheel Alignment' },
    { id: 'windshield_wipers', name: 'Windshield Wipers' }
]; 